language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
script: python tests/test_wavefront.py
install:
  - pip install .
  - pip install -r requirements.txt
branches:
  only:
    - master