language: python
python:
  - "2.7"
  - "3.4"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: python -m unittest
install:
  - pip install .
  - pip install -r requirements.txt
branches:
  only:
    - master